# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TJSocial' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

end
